### PR TITLE
Fix/stop after winning

### PR DESCRIPTION
**Pull request by waqas-334**
Stop playing after someone won the game or if it ended in Tie

### CODE REVIEW

**Comment by waqas-334** [comment]
The first commit just added so many unnecessary changes because auto-indentation in VS Code, but the only logic is a variable that store if someone won or not, if someone did win then stop adding X or Os

**Comment by canankorkut** [comment]
Thank you for your contribution! I have included your changes in the project.

**Comment by waqas-334** [comment]
Thank you, I also added code to make it multiplayer, the code is available here: https://github.com/waqas-334/TicTacToe-web/tree/feature/backend

Feel free to check it out ;)

**Comment by canankorkut** [comment]
I'll check out the code. Appreciate your contribution! :)

**Pull request merged**
